/// <reference types="node" />
import { describe, it, expect, afterAll } from 'vitest';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { calculateAll, registry, parseCsv, parseWideRow } from '../src/index';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');
const csv = parseCsv(readFileSync(resolve(root, 'validation/fixtures/inputs.csv'), 'utf8'));
const legacy = JSON.parse(readFileSync(resolve(root, 'validation/fixtures/insusenscalc_0.1.0.json'), 'utf8')) as {
  rows: Record<string, number | string | null>[];
};
const rows = csv.map((r) => parseWideRow(r));
const legacyById = new Map(legacy.rows.map((r) => [String(r.participant_id), r]));

const relDiff = (a: number, b: number) => Math.abs(a - b) / Math.max(Math.abs(a), Math.abs(b), 1e-300);

const diffRows: string[] = [];
const unavailRows: string[] = [];
let matched = 0;
const counts = new Map<string, number>();

describe('ISAT vs InsuSensCalc 0.1.0', () => {
  for (const row of rows) {
    const id = row.participant_id!;
    const leg = legacyById.get(id)!;
    const results = calculateAll(row.inputs);
    it(`${id}: one result per method, no parse problems`, () => {
      expect(row.problems).toEqual([]);
      expect(results.length).toBe(registry.length);
    });
    for (const m of registry) {
      const r = results.find((x) => x.id === m.id)!;
      if (m.legacy.relation === 'none') continue;
      const col = typeof m.legacy.column === 'string' ? m.legacy.column : m.legacy.column?.[row.inputs.sex!];
      const L = col ? (leg[col] as number | null | undefined) ?? null : null;
      it(`${id} ${m.id} (${m.legacy.relation}, ${col})`, () => {
        if (r.status !== 'ok') {
          // unavailable: legacy must be null, or ISAT must name the missing inputs
          expect(r.status).toBe('unavailable');
          expect(r.reasons.length).toBeGreaterThan(0);
          unavailRows.push(`| ${id} | ${m.id} | ${r.reasons.join('; ')} | ${L === null ? 'null' : L} |`);
          expect(L === null || r.reasons.every((x) => x.startsWith('requires'))).toBe(true);
          return;
        }
        const v = r.value as number;
        if (m.legacy.relation === 'equal' || m.legacy.relation === 'negated') {
          expect(L, 'legacy value present').not.toBeNull();
          const expected = m.legacy.relation === 'negated' ? -(L as number) : (L as number);
          expect(relDiff(v, expected), `ISAT ${v} vs legacy-derived ${expected}`).toBeLessThan(1e-9);
          matched++;
          counts.set(m.id, (counts.get(m.id) ?? 0) + 1);
        } else {
          expect(m.legacy.relation).toBe('different');
          if (L !== null) {
            expect(relDiff(v, L)).toBeGreaterThan(1e-9);
            diffRows.push(`| ${id} | ${m.id} | ${v} | ${L} |`);
          }
        }
      });
    }
  }

  it('sanity: Cederholm > 0 for all rows; legacy is negative for EX1', () => {
    for (const row of rows) {
      const r = calculateAll(row.inputs).find((x) => x.id === 'cederholm')!;
      expect(r.status).toBe('ok');
      expect(r.value as number).toBeGreaterThan(0);
    }
    expect(legacyById.get('EX1')!['Cederholm_index'] as number).toBeLessThan(0);
  });

  it('sanity: Belfiore ISI(gly) in (0, 2) for NGT rows, with reference set recorded', () => {
    for (const row of rows.filter((r) => r.participant_id!.startsWith('NGT'))) {
      const r = calculateAll(row.inputs).find((x) => x.id === 'belfiore_isi_gly')!;
      expect(r.status).toBe('ok');
      expect(r.value as number).toBeGreaterThan(0);
      expect(r.value as number).toBeLessThan(2);
      expect((r.details?.reference_set as { name: string }).name).toBe('belfiore_1998');
    }
  });

  afterAll(() => {
    const md = [
      '# ISAT vs InsuSensCalc 0.1.0: intentional differences',
      '',
      'Generated by `packages/core/test/legacy.test.ts`; do not edit by hand.',
      `Methods x rows matching legacy (equal/negated, rel. tol 1e-9): ${matched}.`,
      '',
      '## Methods with legacy relation `different`',
      '',
      '| row | method | ISAT value | legacy value |',
      '|---|---|---|---|',
      ...diffRows,
      '',
      '## ISAT unavailable (reason given; legacy value shown)',
      '',
      '| row | method | ISAT reasons | legacy value |',
      '|---|---|---|---|',
      ...unavailRows,
      '',
    ].join('\n');
    mkdirSync(resolve(root, 'validation'), { recursive: true });
    writeFileSync(resolve(root, 'validation/legacy-differences.md'), md);
    console.log(`legacy matches: ${matched}; different rows: ${diffRows.length}; unavailable: ${unavailRows.length}`);
    console.log([...counts].map(([k, v]) => `${k}:${v}`).join(' '));
  });
});
