// Parses methods/*.yaml into src/generated/methods.ts (pure data; no runtime deps in src).
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { parse } from 'yaml';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(root, 'methods');
const out = {};
for (const f of readdirSync(dir).filter((f) => f.endsWith('.yaml')).sort()) {
  out[f.replace(/\.yaml$/, '')] = parse(readFileSync(join(dir, f), 'utf8'));
}
mkdirSync(join(root, 'src', 'generated'), { recursive: true });
writeFileSync(
  join(root, 'src', 'generated', 'methods.ts'),
  `// AUTO-GENERATED by scripts/gen-methods.mjs from methods/*.yaml. Do not edit.\nexport const methodSpecs = ${JSON.stringify(out, null, 2)} as const;\n`,
);
