// Generates docs/derivation-populations.md from the method files (the same source the website uses).
// Written by scripts/gen-docs.ts (npm run docs); packages/core/test/populations-doc.test.ts fails if the file is out of date.
import { registry, methodSpecs } from '../packages/core/src/index';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Spec = Record<string, any>;

const CATEGORIES: Array<[string, string]> = [
  ['fasting', 'Fasting'], ['ogtt', 'OGTT'], ['lipid', 'Lipid & body measures'], ['tracer_dxa', 'Tracer & DXA'],
];

function flatSpecs(): Record<string, Spec> {
  const flat: Record<string, Spec> = {};
  for (const spec of Object.values(methodSpecs) as unknown as Spec[]) {
    if (Array.isArray(spec.methods)) {
      const { methods, ...group } = spec;
      for (const m of methods) flat[m.id] = { ...group, ...m };
    } else flat[spec.id] = spec;
  }
  return flat;
}

function shortCite(spec: Spec): string {
  const c: string = spec.reference?.citation ?? (typeof spec.source === 'object' ? spec.source?.citation : '') ?? '';
  const author = /^([^,\s]+)/.exec(c)?.[1] ?? '';
  const year = /\b(19|20)\d{2}\b/.exec(c)?.[0] ?? '';
  return `${author} ${year}`.trim();
}

const cell = (s: unknown) => String(s ?? '').replace(/\|/g, '\\|').replace(/\s+/g, ' ').trim();

export function populationsMarkdown(): string {
  const flat = flatSpecs();
  const included = registry.filter((m) => m.deferredReason === undefined);
  const out: string[] = [
    '# Derivation populations',
    '',
    '<!-- Generated by scripts/gen-docs.ts from packages/core/methods/*.yaml. Do not edit by hand: run `npm run docs`. -->',
    '',
    'Where each index in ISAT was developed, as reported in its original paper. "Place" is the study centre. Most papers do not report ancestry.',
    '',
    '- Most indices come from single cohorts, mostly in Europe or the USA, with a few hundred people or fewer. Their behaviour in other populations has often not been studied.',
    '- Compare values within your own study rather than with values or thresholds from other populations.',
    '- In genetic or epidemiological work, account for ancestry in the analysis (for example genetic principal components or stratification), not by changing the index.',
    '- Insulin assays differ between laboratories, so values from different studies are only approximately comparable.',
    '',
    'The same information is shown with every result and on the [Methods page](https://sufyansuleman.github.io/isat/#/methods) of the web app.',
  ];
  for (const [cat, label] of CATEGORIES) {
    const ms = included.filter((m) => m.category === cat);
    if (!ms.length) continue;
    out.push('', `## ${label}`, '', '| Index | Population | N | Place | Original paper |', '|---|---|---|---|---|');
    for (const m of ms) {
      const spec = flat[m.id] ?? {};
      const d = spec.derived_in ?? {};
      out.push(`| ${cell(m.name)} | ${cell(d.population ?? 'not recorded')} | ${cell(d.n)} | ${cell(d.setting)} | ${cell(shortCite(spec))} |`);
    }
  }
  return out.join('\n') + '\n';
}

